#!/usr/bin/env bash

#
# Copyright 2020, TeamDev. All rights reserved.
#
# Redistribution and use in source and/or binary forms, with or without
# modification, must retain the above copyright notice and the following
# disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

################################################################################
#
# The script to update the project configuration files.
#
# The code of the script assumes that:
#   1. The project uses this code as a Git sub-module installed in the `config`
#      directory under the project root.
#   2. The script is called from the root of the project.
#
################################################################################

# Update the module with reference to the latest version.
# In this state there is no current branch.
git submodule update

# Make the `config` dir current.
cd ./config

# Set the current branch to master.
git checkout master

echo "Pulling changes from remote repo"
git pull

echo "Updating IDEA configuration"
cp -R .idea ..

echo "Updating CI config files"
cp .codecov.yml ..
cp .gitattributes ..

# Copy `.gitignore` only if it's not yet created.
if [ ! -f ../.gitignore ]; then
    echo "Creating .gitignore"
    cp .gitignore ..
fi

# Copy `version.gradle` only if it is not yet created in the project.
if [ ! -f ../version.gradle ]; then
    echo "Creating version.gradle"
    cp version.gradle ..
fi

cd ..

echo "Done."
