#!/bin/bash

# Find and print all the Markdown files in current directory.
#
# Outputs the absolute paths to the files.
#
# Filters out `README.md` files and files under `_site/` directory.
#
find $(pwd) -iname '*.md' |
 grep --invert-match ".*/README\.md" |
 grep --invert-match ".*/_site/\.*"
