#!/bin/bash

cd _examples || exit
pub get

# Ensure that all the code snippets are up to date.
#
# Exits with a non-0 code if any updates are not done.
#
pub run code_excerpt_updater ../ --fail-on-refresh  --yaml  --fragment-dir-path ./.excerpt/examples/
