#!/bin/bash

# Load environment variables for the case of execution from the Gradle build.
source ~/.bash_profile

# Ensure `_code` files are fetched.
git submodule update --init --recursive

# Update code samples.
bundle exec jekyll embedCodeSamples
