#!/usr/bin/env bash

# Load environment variables for the case of execution from the Gradle build if they exist.
BASH_PROFILE=~/.bash_profile
BASH_RC=~/.bashrc

if [ -f ${BASH_PROFILE} ]; then
  echo "Using user's local bash profile."
  . ${BASH_PROFILE}
elif [ -f ${BASH_RC} ]; then
  echo "Using user's local bash runtime configuration."
  . ${BASH_RC}
fi

# Ensure `_code` files are fetched.
git submodule update --remote --merge --recursive

# Update code samples.
bundle exec jekyll embedCodeSamples
