#!/bin/bash

# Find all `.md` files.
#
# The resiulting array stores absolute paths to all Markdown files in current directory.
#
allMarkdown=$(eval "$(pwd)/_script/all_markdown")

cd _examples || exit
pub get

# Update excerpt intex.
pub run build_runner build --output=.excerpt --config=excerpt

# Update code snippets in documentation files.
#
# Ignores `README` files and the already generated `_site`.
#
pub run code_excerpt_updater \
  $allMarkdown \
  --write-in-place --yaml \
  --fragment-dir-path ./.excerpt/examples/
