[params.payment]
  consentURL = 'http://localhost:5002/spine-site-server/us-central1/api/consent'
  paygateURL = 'https://stag.paygate.teamdev.com'
  standardSupportProductId = '137c613b-305b-45ce-bd40-49f6a42eafde'
