name: Check Code Embedding

on:
  push:
    branches:
      - all
  pull_request:
    branches:
      - master

jobs:

  build-embedded-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: zulu

      - run: ./gradlew :buildAll

  check-embedded-samples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.4'

      # Bundler version is restricted to `2.4.22`,
      # as we want to use Ruby `2.7.4` to match GH Pages environment.
      #
      # Any newer versions of Bundler require Ruby 3.x,
      # which are much newer than what's GH Pages has at the moment.
      #
      - run: |
          gem install bundler -v 2.4.22
          bundle install

      - name: Check Embedding
        run: ./_script/check-samples
