name: Check Code Embedding

on:
  push:
    branches:
      - all
  pull_request:
    branches:
      - master

jobs:

  build-embedded-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: zulu

      - run: ./gradlew :buildAll

  check-embedded-samples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.4'

      - run: |
          gem install bundler
          bundle install

      - name: Check Embedding
        run: ./_script/check-samples
