name: Site checks

on: push

jobs:
  check-site:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - run: ./_script/check

  check-examples:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - run: git submodule update --init --recursive
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: ./gradlew build
