name: Site checks

on:
  push:
    branches:
      - all
  pull_request:
    branches:
      - master

jobs:
  check-site:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Ruby and Bundler
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7.x'
        run: |
          gem install bundler
          bundle install

      - run: ./_script/check

  check-examples:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - run: git submodule update --init --recursive
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: ./gradlew :buildAll
