name: Links check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6.x'

      - name: Run Jekyll build
        run: |
          gem install bundler
          bundle install
          jekyll build
          htmlproofer --assume-extension ./_site --url-ignore /github\.com/
